// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa8oEpYw2DYndjzzP4yoLGNJl0Arw-DmQ',
    appId: '1:185424047153:web:d214a4f37d82ccc774b910',
    messagingSenderId: '185424047153',
    projectId: 'red-it-d87d6',
    authDomain: 'red-it-d87d6.firebaseapp.com',
    storageBucket: 'red-it-d87d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPUf7Ah4obBZ4GiM8cmRDtHgKBiwLYofU',
    appId: '1:185424047153:android:124a2a9c5bfea7e174b910',
    messagingSenderId: '185424047153',
    projectId: 'red-it-d87d6',
    storageBucket: 'red-it-d87d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBat4YaMOBOpuXQ_6agHC-XAxbj0RuaMk4',
    appId: '1:185424047153:ios:a64d5010c727465d74b910',
    messagingSenderId: '185424047153',
    projectId: 'red-it-d87d6',
    storageBucket: 'red-it-d87d6.appspot.com',
    iosClientId: '185424047153-i99imphuj12mbcvfj12nqc5vg1cqm6j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.redIt',
  );
}
